'use client'
import { useState } from 'react'
import { SUPPORTED_LANGUAGES, type LangCode } from '@/lib/gemma'
import type { NDVIResult } from '@/pages/api/ndvi'
import type { GemmaResponse } from '@/lib/gemma'

type FullResult = NDVIResult & GemmaResponse

interface Props {
  district: string
  result: FullResult
}

export default function ReportDownload({ district, result }: Props) {
  const [lang, setLang] = useState<LangCode>('en')
  const [generating, setGenerating] = useState(false)

  const handleDownload = async () => {
    setGenerating(true)
    try {
      const englishText = buildReportText(district, result)
      const finalText = lang === 'en' ? englishText : await fetchTranslation(englishText, lang)
      await generatePDF(district, result, finalText, lang)
    } finally {
      setGenerating(false)
    }
  }

  return (
    <div style={{ padding: '0 12px 16px', marginTop: 'auto' }}>
      <div style={{ marginBottom: '8px' }}>
        <label style={{ fontSize: '11px', color: '#9ca3af', display: 'block', marginBottom: '4px' }}>
          Report language
        </label>
        <select
          value={lang}
          onChange={e => setLang(e.target.value as LangCode)}
          style={{
            width: '100%', padding: '7px 10px', fontSize: '12px',
            border: '1px solid #e5e7eb', borderRadius: '6px',
            background: '#f9fafb', color: '#111827', cursor: 'pointer',
          }}
        >
          {SUPPORTED_LANGUAGES.map(l => (
            <option key={l.code} value={l.code}>
              {l.nativeName} — {l.label}
            </option>
          ))}
        </select>
      </div>

      <button
        onClick={handleDownload}
        disabled={generating}
        style={{
          width: '100%', padding: '9px', border: '1px solid #e5e7eb',
          borderRadius: '8px',
          background: generating ? '#f3f4f6' : '#f9fafb',
          cursor: generating ? 'wait' : 'pointer',
          fontSize: '13px', color: '#374151', fontWeight: 500,
        }}
      >
        {generating ? 'Generating report...' : 'Download PDF policy brief'}
      </button>
    </div>
  )
}

function buildReportText(district: string, result: FullResult): string {
  const zones = result.verified_zones ?? []
  const recs = result.mode === 'planting'
    ? zones.map((z, i) =>
        `${i + 1}. ${z.planting_method} at ${z.site_type.replace('_', ' ')} — ` +
        `${z.estimated_trees.toLocaleString()} trees, estimated cooling ${z.cooling_impact}. ` +
        `${z.gemma_reasoning}.`
      ).join('\n')
    : [
        `1. Rooftop greening: ${result.available_rooftops} eligible rooftops identified`,
        `2. Roadside planting: ${result.road_km} km of eligible road corridors`,
        `3. Vertical wall gardens: ${result.wall_count} suitable building facades`,
        `4. Parking lot greening: ${result.parking_lots} lots for perimeter planting`,
      ].join('\n')

  return `DELHI URBAN FOREST INTELLIGENCE
Policy Brief — ${district}
Generated by Gemma 4 | Global Resilience Track

ZONE STATISTICS
Canopy Cover: ${result.canopy_pct}%
Surface Temperature: ${result.avg_temp_c}°C
Built-up Area: ${result.built_up_pct}%
Barren Land Available: ${result.barren_ha} hectares

GEMMA 4 ANALYSIS
${result.analysis}

RECOMMENDATIONS
${recs}

---
Powered by Gemma 4 multimodal AI and Google Earth Engine Sentinel-2 data.
Delhi Urban Forest Intelligence — Gemma 4 Impact Challenge`
}

async function fetchTranslation(text: string, lang: LangCode): Promise<string> {
  try {
    const res = await fetch('/api/translate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ text, lang }),
    })
    const data = await res.json()
    return data.translated ?? text
  } catch {
    return text
  }
}

async function generatePDF(
  district: string,
  result: FullResult,
  text: string,
  lang: LangCode
) {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF()
  const langLabel = SUPPORTED_LANGUAGES.find(l => l.code === lang)?.label ?? 'English'

  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('Delhi Urban Forest Intelligence', 20, 20)

  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100)
  doc.text(`Policy Brief — ${district}`, 20, 29)
  doc.text(`Language: ${langLabel} | Powered by Gemma 4`, 20, 36)
  doc.text(`Generated: ${new Date().toLocaleDateString('en-IN', {
    day: 'numeric', month: 'long', year: 'numeric',
  })}`, 20, 43)

  doc.setDrawColor(200)
  doc.line(20, 47, 190, 47)

  doc.setFontSize(10)
  doc.setTextColor(40)
  const lines = doc.splitTextToSize(text, 170)
  doc.text(lines, 20, 55)

  doc.setFontSize(8)
  doc.setTextColor(160)
  doc.text(
    'Delhi Urban Forest Intelligence · Gemma 4 Impact Challenge · Global Resilience Track',
    20, 285
  )

  doc.save(`delhi-forest-${district.replace(/\s+/g, '-').toLowerCase()}-${lang}.pdf`)
}
